clairebot.version=${version}
clairebot.buildDate=${buildDate}
clairebot.github=https://github.com/Sidpatchy/ClaireBot
clairebot.supportServer=https://support.clairebot.net/
clairebot.inviteLink=https://invite.clairebot.net/
clairebot.website="https://www.clairebot.net/
clairebot.documentationWebsite=https://docs.clairebot.net/