# ----------------------------------------------
# |             ClaireBot v3.2.0               |
# |                Config file                 |
# ----------------------------------------------

# ----------------- MAIN CONFIG ----------------
# General config options

# Discord bot token, get one at https://discord.com/developers/applications
token:

# URL of the YouTube video ClaireBot claims to be streaming
video_url: https://www.youtube.com/watch?v=AeZRYhLDLeU

# Colours to use in the bot's embeds
color: "#3498db"
errorColor: "#e74d3c"

# URLs for GIFS to randomly use in the error embed.
error_gifs:
  - "https://c.tenor.com/FcVg5W9zZJQAAAAC/error.gif"
  - "https://c.tenor.com/2gdcdzl-xaoAAAAC/error-computer.gif"
  - "https://c.tenor.com/V7ShPyRtBioAAAAC/cat-fail.gif"
  - "https://c.tenor.com/4VY0Ykn4lN4AAAAC/cat-broken-cat.gif"
  - "https://c.tenor.com/fKIG2kiLVPgAAAAC/this-is-fine-its-fine.gif"
  - "https://c.tenor.com/Yv2ty8bP3kgAAAAC/noooo-no.gif"
  - "https://c.tenor.com/8_0RIO8A__cAAAAC/personal-problem-sounds-like-a-personal-problem.gif"
  - "https://c.tenor.com/hywZNm_1efkAAAAC/csgo-banging-table.gif"
  - "https://c.tenor.com/GBrG7SqlVwoAAAAC/dog-dawg.gif"
  - "https://c.tenor.com/lRhsxkfHhJwAAAAC/spongebob-squarepants-sad.gif"

# The language ClaireBot will fallback to if a translation string
# is not available for a user's chosen language.
fallback_language: en-US

# ----------------- SHARD CONFIG ---------------
# It is assumed that only one shard will be running by default.
# You probably don't need to change this.

# The shard the bot should log in to
current_shard: 0

# The total number of shards.
total_shards: 1

# --------------- DATABASE CONFIG --------------
# Config options related to ClaireData.
# https://github.com/Sidpatchy/ClaireData

# ClaireData's login information
apiPath: http://clairedata:8080/
apiUser: clairedata
apiPassword: examplePassword

# Determines whether failing to connect to the ClaireData API is fatal. This is only checked when the bot is started.
# Recommend leaving enabled unless you are developing ClaireBot & need to bypass this check.
apiFailureIsFatal: true

userDefaults:
  accentColour: "#3498db"
  language: "en-US"
  pointsGuildID:
    - |
      {"global": 0}
  pointsMessages: [0]
  pointsVoiceChat: [0]

guildDefaults:
  requestsChannelID: null
  moderatorMessagesChannelID: null
  enforceServerLanguage: false

# ------------------- ZERFAS -------------------
# https://en.wikipedia.org/wiki/Zerfas_(band)
#
# You will need to create a Zerfas emoji in a server YOU own, and copy the server and emoji ID here.
# An emoji is provided here: https://github.com/Sidpatchy/ClaireBot/tree/main/img
#
# You can realistically modify this to work for anything you want. Just change the triggers under 'zerfas'

# List of things to react to with the Zerfas emote
zerfas:
  - "YOU NEVER WIN"
  - "THE SWEETEST PART"
  - "I DON'T UNDERSTAND"
  - "I NEED IT HIGHER"
  - "STONEY WELLITZ"
  - "HOPE"
  - "FOOL'S PARADE"
  - "THE PIPER"
  - "CERTAIN KIND OF LADY"
  - "SHAKE UP YOUR MIND"
  - "ZERFAS"
  - "GOOD MUSIC"

zerfas_emoji_server_id:
zerfas_emoji_id:

# -------------------- MISC --------------------
# This section contains values that don't fit in the main categories

# Triggers for the pls ban feature. Ex. @clairebot pls ban the zucc
PlsBanTriggers:
  - "pls ban"
  - "please ban"
  - "ban"

# Responses to the PlsBanTriggers
PlsBanResponses:
  - "i gotchu fam"
  - "No problem!"
  - "Done. Happy to help :)"
  - "Consider it done."
  - "It's done. RIP BOZO"
  - "*L + Ratio -ClaireBot*"
  - "I'll tell them to kick rocks, I guess ¯\\_(ツ)_/¯"
  - "Sand has been shipped to their location. Gift note: \"Pound sand\""
  - "Cry harder."
  - "K"
  - "Good riddance"

# Controls whether the bot should check for updates.
checkForUpdates: true

# Whether the bot should attempt to update or fix broken configuration files on startup or reloads.
UpdateOutdatedConfigs: true

# Do not change this, this is automatically changed when needed.
# TODO either automatically add new config file params or remove this.
configRevision: 5

# ---------- ADDED AFTER INITIAL USE -----------
# Parameters that were added to the config file after it was initially generated